language: php

php:
  - 7.2
  - 7.3

env:
  - COMPOSER_DEPENDENCIES=""
  - COMPOSER_DEPENDENCIES="--prefer-lowest"

install:
  - travis_retry composer update --no-interaction $COMPOSER_DEPENDENCIES

script:
  - composer run build
